# Generated by Django 5.1.5 on 2025-02-05 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('admin_name', models.CharField(max_length=100)),
                ('admin_email', models.CharField(max_length=100, unique=True)),
                ('admin_password', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'admin',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BooksCategory',
            fields=[
                ('bookscategory_id', models.AutoField(primary_key=True, serialize=False)),
                ('bookscategory_name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'books_category',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('customer_city', models.CharField(blank=True, max_length=50, null=True)),
                ('customer_remarks', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'customer',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_type', models.CharField(max_length=11)),
                ('user_id', models.IntegerField()),
                ('message', models.TextField()),
                ('event_type', models.CharField(max_length=9)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(default='Unread', max_length=6)),
            ],
            options={
                'db_table': 'notification',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('book_name', models.CharField(max_length=200)),
                ('book_author', models.CharField(blank=True, max_length=100, null=True)),
                ('book_language', models.CharField(max_length=50)),
                ('book_price', models.IntegerField()),
                ('book_category', models.ForeignKey(blank=True, db_column='book_category', null=True, on_delete=django.db.models.deletion.CASCADE, to='bm_app.bookscategory', to_field='bookscategory_name')),
            ],
            options={
                'db_table': 'books',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Distributor',
            fields=[
                ('distributor_id', models.AutoField(primary_key=True, serialize=False)),
                ('distributor_name', models.CharField(max_length=100)),
                ('distributor_phonenumber', models.CharField(db_column='distributor_phoneNumber', max_length=15)),
                ('distributor_address', models.TextField(blank=True, null=True)),
                ('distributor_email', models.CharField(max_length=100)),
                ('distributor_password', models.CharField(max_length=100)),
                ('distributor_age', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='bm_app.admin')),
            ],
            options={
                'db_table': 'distributor',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DistributorInventory',
            fields=[
                ('inventory_id', models.AutoField(primary_key=True, serialize=False)),
                ('books_stock', models.IntegerField(default=0)),
                ('books', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bm_app.books')),
                ('distributor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bm_app.distributor')),
            ],
            options={
                'db_table': 'distributor_inventory',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('donation_id', models.AutoField(primary_key=True, serialize=False)),
                ('donation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('donation_amount', models.IntegerField()),
                ('donation_purpose', models.CharField(blank=True, max_length=100, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='bm_app.customer')),
            ],
            options={
                'db_table': 'donation',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MasterInventory',
            fields=[
                ('inventory_id', models.AutoField(primary_key=True, serialize=False)),
                ('stock', models.IntegerField(default=0)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='bm_app.admin')),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='bm_app.books')),
            ],
            options={
                'db_table': 'master_inventory',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('receipt_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('quantity', models.IntegerField()),
                ('payment_mode', models.CharField(blank=True, choices=[('ONLINE', 'Online'), ('CASH', 'Cash')], db_column='paymentMode', max_length=6, null=True)),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='bm_app.books')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='bm_app.customer')),
                ('distributor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='bm_app.distributor')),
                ('donation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bm_app.donation')),
            ],
            options={
                'db_table': 'receipt',
                'managed': True,
            },
        ),
    ]
