# Generated by Django 5.1.5 on 2025-02-06 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bm_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='distributor',
            options={'managed': False},
        ),
    ]
