# Generated by Django 5.1.5 on 2025-01-23 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bm_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('book_name', models.CharField(max_length=200)),
                ('book_author', models.CharField(blank=True, max_length=100, null=True)),
                ('book_language', models.CharField(max_length=50)),
                ('book_price', models.IntegerField()),
            ],
            options={
                'db_table': 'books',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BooksCategory',
            fields=[
                ('bookscategory_id', models.AutoField(primary_key=True, serialize=False)),
                ('bookscategory_name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'books_category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_phone', models.CharField(blank=True, max_length=10, null=True)),
                ('customer_city', models.CharField(blank=True, max_length=50, null=True)),
                ('customer_remarks', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'customer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Distributor',
            fields=[
                ('distributor_id', models.AutoField(primary_key=True, serialize=False)),
                ('distributor_name', models.CharField(max_length=100)),
                ('distributor_phonenumber', models.CharField(db_column='distributor_phoneNumber', max_length=10)),
                ('distributor_address', models.TextField(blank=True, null=True)),
                ('distributor_email', models.CharField(max_length=100)),
                ('distributor_password', models.CharField(max_length=100)),
                ('distributor_age', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'distributor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DistributorInventory',
            fields=[
                ('inventory_id', models.AutoField(primary_key=True, serialize=False)),
                ('books_stock', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'distributor_inventory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('donation_id', models.AutoField(primary_key=True, serialize=False)),
                ('donation_date', models.DateTimeField(blank=True, null=True)),
                ('donation_amount', models.IntegerField()),
                ('donation_purpose', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'donation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MasterInventory',
            fields=[
                ('inventory_id', models.AutoField(primary_key=True, serialize=False)),
                ('stock', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'master_inventory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_type', models.CharField(choices=[('admin', 'Admin'), ('distributor', 'Distributor')], max_length=11)),
                ('user_id', models.IntegerField()),
                ('message', models.TextField()),
                ('event_type', models.CharField(choices=[('low stock', 'Low Stock'), ('others', 'Others')], max_length=9)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('read', 'Read'), ('unread', 'Unread')], max_length=6, null=True)),
            ],
            options={
                'db_table': 'notification',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('receipt_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('quantity', models.IntegerField()),
                ('paymentmode', models.CharField(blank=True, choices=[('online', 'Online'), ('cash', 'Cash')], db_column='paymentMode', max_length=6, null=True)),
            ],
            options={
                'db_table': 'receipt',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='admin',
            options={'managed': False},
        ),
    ]
