# Generated by Django 5.1.5 on 2025-01-27 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bm_app', '0002_books_bookscategory_customer_distributor_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='admin',
            table='admin',
        ),
    ]
