# Generated by Django 5.1.5 on 2025-01-29 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bm_app', '0003_alter_admin_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'managed': True},
        ),
    ]
