# Generated by Django 5.1.5 on 2025-01-29 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bm_app', '0004_alter_customer_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='receipt',
            options={'managed': True},
        ),
    ]
