# Generated by Django 5.1.5 on 2025-01-29 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bm_app', '0005_alter_receipt_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='receipt',
            options={'managed': False},
        ),
    ]
